<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://transconnect.io/connector/mcp/execute/out"
            xmlns="http://transconnect.io/connector/mcp/execute/out"
            elementFormDefault="qualified">

    <xsd:simpleType name="name">
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>

    <xsd:element name="ROOT">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="RETURN" minOccurs="1" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="DATA" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                        </xsd:sequence>
                        <xsd:attribute name="NAME" type="name"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>